name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python for node-gyp
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Make (Windows only)
        if: runner.os == 'Windows'
        run: choco install make

      - name: Install Dependencies
        run: npm install --no-package-lock
        
      - name: Build JS
        run: npm run build
        
      # electron-builder automatically marks the release as a pre-release on GitHub 
      # if the version in package.json contains a hyphen (e.g. -beta, -alpha, -rc).
      
      - name: Package & Publish (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --mac --publish always


      - name: Package & Publish (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --linux --publish always
